"""fn-147.1 — interview emits source tags, and cannot drift from capture's vocabulary.

`/flow-next:refine` writes acceptance criteria with the same trailing-token
provenance tags `/flow-next:capture` writes (`[user]` / `[paraphrase]` /
`[inferred]` / `[strategy:<track>]`). The vocabulary is deliberately REPEATED at
each emission site rather than centralised (fn-84.2 relocated capture's tables as
a "safe" DRY trim, regressed a fixture 15 -> 14, and was reverted — proximity is
accuracy-load-bearing). So "cannot drift" is enforced here: the same tag
vocabulary on both sides (the user's verbatim words stay untagged in both).
flowctl's export parses the trailing tag token, so the vocabulary is a
contract; the definition sentences are not pinned.

Scope: CANONICAL skill files only. The Codex mirror is regenerated by
sync-codex.sh and is not asserted here.
"""

from __future__ import annotations

import pathlib
import re
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
PLUGIN = REPO_ROOT / "plugins" / "flow-next"
SKILLS = PLUGIN / "skills"

# Capture's source-tag taxonomy lives as a single copy in phases.md.
CAPTURE_PHASES = SKILLS / "flow-next-capture" / "phases.md"
INTERVIEW_WRITE_BACK = (
    SKILLS / "flow-next-refine" / "references" / "write-back.md"
)

TAGS = ("[user]", "[paraphrase]", "[inferred]", "[strategy:<track>]")
# Capture tags only what it authored; the user's verbatim words carry no tag.
CAPTURE_TAGS = tuple(t for t in TAGS if t != "[user]")

# Header of the source-tag table in every source file. Extraction is anchored to
# it so a sibling table (capture/phases.md's confidence markers) cannot leak in.
_TAG_TABLE_HEADER = re.compile(r"^\|\s*Tag\s*\|\s*Meaning\s*\|", re.MULTILINE)
_TAG_ROW = re.compile(r"^\|\s*`(\[[^\]`]+\])`\s*\|")


def read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


def tag_table_tokens(text: str) -> set[str]:
    """Tag tokens from the source-tag table only.

    Anchors on the `| Tag | Meaning |` header, skips the `|---|` rule, then
    consumes contiguous table rows until the table ends. Returns a set so the
    caller can assert equality (catching additions, not just absences).
    """
    m = _TAG_TABLE_HEADER.search(text)
    if not m:
        return set()
    tokens: set[str] = set()
    for line in text[m.end() :].split("\n")[1:]:  # [1:] skips the |---| rule
        if not line.startswith("|"):
            break
        row = _TAG_ROW.match(line)
        if row:
            tokens.add(row.group(1))
    return tokens


_TAG_BULLET = re.compile(r"^- `(\[[^\]`]+\])` ", re.MULTILINE)


def tag_list_tokens(text: str) -> set[str]:
    """Tag tokens from a `## Source tags` bullet list (refine's form)."""
    start = text.find("## Source tags")
    if start < 0:
        return set()
    nxt = text.find("\n## ", start + 1)
    section = text[start : nxt if nxt > 0 else len(text)]
    return set(_TAG_BULLET.findall(section))


class InterviewSourceTagsTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.capture_phases = read(CAPTURE_PHASES)
        cls.write_back = read(INTERVIEW_WRITE_BACK)

    def test_tag_vocabulary_matches_capture(self) -> None:
        """Neither skill can rename, drop, OR ADD a tag token alone.

        Set-EQUALITY, not presence: a presence-only assertion structurally
        cannot catch an ADDITION (a fifth tag on one side leaves every existing
        assertion green). Extraction is scoped to each file's source-tag table
        because `capture/phases.md` carries a SECOND table of confidence
        markers (`[high]` / `[judgment-call]` / `[your-call]`) that would
        otherwise contaminate the set.
        """
        sources = {
            "capture/phases.md": (self.capture_phases, CAPTURE_TAGS),
            "interview/references/write-back.md": (self.write_back, CAPTURE_TAGS),
        }
        for label, (text, expected) in sources.items():
            with self.subTest(file=label):
                found = tag_table_tokens(text) or tag_list_tokens(text)
                self.assertEqual(
                    found,
                    set(expected),
                    f"{label} source-tag table is {sorted(found)}, expected "
                    f"{sorted(expected)} — the shared vocabulary has drifted "
                    f"(a renamed, dropped, or ADDED tag all land here)",
                )

    # --- R5: tags discriminate on the frozen fixture ------------------------

if __name__ == "__main__":
    unittest.main()
